stages:
  - name: Build & Publish
    when:
      branch: master
      event: [push, pull request]
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: bday-emails:${CICD_EXECUTION_SEQUENCE}
        env:
          PLUGIN_MTU: 1450
  - name: Deploy
    when:
      branch: master
      event: [push, pull request]
    steps:
      - applyYamlConfig:
          path: ./bday-reminder-dc.yaml
