stages:
- name: Build & Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: bday-emails:${CICD_EXECUTION_SEQUENCE}
    env:
      PLUGIN_MTU: 1450
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./bday-reminder-dc.yaml